kubectl apply -f airflow-envvars-configmap.yaml
kubectl apply -f airflow-logs-volume.yaml
kubectl apply -f airflow-req-configmap.yaml
kubectl apply -f airflow-scheduler-deployment.yaml
kubectl apply -f airflow-scheduler-permissions.yaml
kubectl apply -f airflow-webserver-deployment.yaml
kubectl apply -f airflow-webserver-service.yaml
kubectl apply -f postgres-deployment.yaml
kubectl apply -f postgres-service.yaml